/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProblemsIdRouteImport } from './routes/problems.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProblemsRouteImport } from './routes/admin.problems'
import { Route as AdminProblemsIndexRouteImport } from './routes/admin.problems.index'
import { Route as AdminProblemsNewRouteImport } from './routes/admin.problems.new'
import { Route as AdminProblemsIdRouteImport } from './routes/admin.problems.$id'
import { Route as AdminNotifyRouteImport } from './routes/admin.notify'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProblemsIdRoute = ProblemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProblemsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsRoute = AdminProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsIndexRoute = AdminProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProblemsRoute,
} as any)
const AdminProblemsNewRoute = AdminProblemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProblemsRoute,
} as any)
const AdminProblemsIdRoute = AdminProblemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProblemsRoute,
} as any)
const AdminNotifyRoute = AdminNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/problems': typeof AdminProblemsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/admin/problems/$id': typeof AdminProblemsIdRoute
  '/admin/problems/new': typeof AdminProblemsNewRoute
  '/admin/problems/': typeof AdminProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/admin': typeof AdminIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/admin/problems/$id': typeof AdminProblemsIdRoute
  '/admin/problems/new': typeof AdminProblemsNewRoute
  '/admin/problems': typeof AdminProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/problems': typeof AdminProblemsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/admin/problems/$id': typeof AdminProblemsIdRoute
  '/admin/problems/new': typeof AdminProblemsNewRoute
  '/admin/problems/': typeof AdminProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/problems'
    | '/profile'
    | '/signup'
    | '/admin/problems'
    | '/admin/users'
    | '/problems/$id'
    | '/admin/'
    | '/problems/'
    | '/admin/problems/$id'
    | '/admin/problems/new'
    | '/admin/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/users'
    | '/admin/notify'
    | '/problems/$id'
    | '/admin'
    | '/problems'
    | '/admin/problems/$id'
    | '/admin/problems/new'
    | '/admin/problems'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/problems'
    | '/profile'
    | '/signup'
    | '/admin/problems'
    | '/admin/users'
    | '/admin/notify'
    | '/problems/$id'
    | '/admin/'
    | '/problems/'
    | '/admin/problems/$id'
    | '/admin/problems/new'
    | '/admin/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problems': {
      id: '/admin/problems'
      path: '/problems'
      fullPath: '/admin/problems'
      preLoaderRoute: typeof AdminProblemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problems/': {
      id: '/admin/problems/'
      path: '/'
      fullPath: '/admin/problems/'
      preLoaderRoute: typeof AdminProblemsIndexRouteImport
      parentRoute: typeof AdminProblemsRoute
    }
    '/admin/problems/new': {
      id: '/admin/problems/new'
      path: '/new'
      fullPath: '/admin/problems/new'
      preLoaderRoute: typeof AdminProblemsNewRouteImport
      parentRoute: typeof AdminProblemsRoute
    }
    '/admin/problems/$id': {
      id: '/admin/problems/$id'
      path: '/$id'
      fullPath: '/admin/problems/$id'
      preLoaderRoute: typeof AdminProblemsIdRouteImport
      parentRoute: typeof AdminProblemsRoute
    }
  }
}

interface AdminProblemsRouteChildren {
  AdminProblemsIdRoute: typeof AdminProblemsIdRoute
  AdminProblemsNewRoute: typeof AdminProblemsNewRoute
  AdminProblemsIndexRoute: typeof AdminProblemsIndexRoute
}

const AdminProblemsRouteChildren: AdminProblemsRouteChildren = {
  AdminProblemsIdRoute: AdminProblemsIdRoute,
  AdminProblemsNewRoute: AdminProblemsNewRoute,
  AdminProblemsIndexRoute: AdminProblemsIndexRoute,
}

const AdminProblemsRouteWithChildren = AdminProblemsRoute._addFileChildren(
  AdminProblemsRouteChildren,
)

interface AdminRouteChildren {
  AdminProblemsRoute: typeof AdminProblemsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminNotifyRoute: typeof AdminNotifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProblemsRoute: AdminProblemsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminNotifyRoute: AdminNotifyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProblemsRouteChildren {
  ProblemsIdRoute: typeof ProblemsIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsIdRoute: ProblemsIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
